// <auto-generated />
using System;
using Credutpay.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Credutpay.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250502081504_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Credutpay.Domain.Registrations.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("WalletId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000001",
                            CreatedAt = new DateTime(2025, 4, 30, 21, 0, 0, 0, DateTimeKind.Local),
                            Email = "admin@credutpay.com",
                            IsDeleted = false,
                            Name = "Administrador",
                            Password = "$2a$11$jOsKulVMar93/ay9GWM6COq.nC3DaEWHQ775T6SOfXj/C70AToWgK",
                            Type = "User",
                            WalletId = "00000000-0000-0000-0000-000000000101"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000002",
                            CreatedAt = new DateTime(2025, 4, 30, 21, 0, 0, 0, DateTimeKind.Local),
                            Email = "lojista@credutpay.com",
                            IsDeleted = false,
                            Name = "Lojista Silva",
                            Password = "$2a$11$jOsKulVMar93/ay9GWM6COq.nC3DaEWHQ775T6SOfXj/C70AToWgK",
                            Type = "User",
                            WalletId = "00000000-0000-0000-0000-000000000102"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000003",
                            CreatedAt = new DateTime(2025, 4, 30, 21, 0, 0, 0, DateTimeKind.Local),
                            Email = "joao@credutpay.com",
                            IsDeleted = false,
                            Name = "João Usuário",
                            Password = "$2a$11$jOsKulVMar93/ay9GWM6COq.nC3DaEWHQ775T6SOfXj/C70AToWgK",
                            Type = "User",
                            WalletId = "00000000-0000-0000-0000-000000000103"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000004",
                            CreatedAt = new DateTime(2025, 4, 30, 21, 0, 0, 0, DateTimeKind.Local),
                            Email = "maria@credutpay.com",
                            IsDeleted = false,
                            Name = "Maria Usuária",
                            Password = "$2a$11$jOsKulVMar93/ay9GWM6COq.nC3DaEWHQ775T6SOfXj/C70AToWgK",
                            Type = "User",
                            WalletId = "00000000-0000-0000-0000-000000000104"
                        });
                });

            modelBuilder.Entity("Credutpay.Domain.Registrations.Entities.Wallet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallet");

                    b.HasData(
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000101",
                            Amount = 5000.00m,
                            CreatedAt = new DateTime(2025, 4, 30, 21, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            UserId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000102",
                            Amount = 10000.00m,
                            CreatedAt = new DateTime(2025, 4, 30, 21, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            UserId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000103",
                            Amount = 1200.50m,
                            CreatedAt = new DateTime(2025, 4, 30, 21, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            UserId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000104",
                            Amount = 850.75m,
                            CreatedAt = new DateTime(2025, 4, 30, 21, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            UserId = "00000000-0000-0000-0000-000000000004"
                        });
                });

            modelBuilder.Entity("Credutpay.Domain.Registrations.Entities.WalletTransaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("WalletReceiverId")
                        .IsRequired()
                        .HasColumnType("character varying(36)");

                    b.Property<string>("WalletSenderId")
                        .IsRequired()
                        .HasColumnType("character varying(36)");

                    b.HasKey("Id");

                    b.HasIndex("WalletReceiverId");

                    b.HasIndex("WalletSenderId");

                    b.ToTable("WalletTransaction");

                    b.HasData(
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000201",
                            Amount = 150.50m,
                            CreatedAt = new DateTime(2025, 4, 26, 21, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            WalletReceiverId = "00000000-0000-0000-0000-000000000102",
                            WalletSenderId = "00000000-0000-0000-0000-000000000103"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000202",
                            Amount = 75.25m,
                            CreatedAt = new DateTime(2025, 4, 28, 21, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            WalletReceiverId = "00000000-0000-0000-0000-000000000102",
                            WalletSenderId = "00000000-0000-0000-0000-000000000104"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000203",
                            Amount = 50.00m,
                            CreatedAt = new DateTime(2025, 4, 30, 21, 0, 0, 0, DateTimeKind.Local),
                            IsDeleted = false,
                            WalletReceiverId = "00000000-0000-0000-0000-000000000104",
                            WalletSenderId = "00000000-0000-0000-0000-000000000103"
                        });
                });

            modelBuilder.Entity("Credutpay.Domain.Registrations.Entities.Wallet", b =>
                {
                    b.HasOne("Credutpay.Domain.Registrations.Entities.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("Credutpay.Domain.Registrations.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Credutpay.Domain.Registrations.Entities.WalletTransaction", b =>
                {
                    b.HasOne("Credutpay.Domain.Registrations.Entities.Wallet", "WalletReceiver")
                        .WithMany("ReceiverTransactions")
                        .HasForeignKey("WalletReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Credutpay.Domain.Registrations.Entities.Wallet", "WalletSender")
                        .WithMany("SentTransactions")
                        .HasForeignKey("WalletSenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WalletReceiver");

                    b.Navigation("WalletSender");
                });

            modelBuilder.Entity("Credutpay.Domain.Registrations.Entities.User", b =>
                {
                    b.Navigation("Wallet")
                        .IsRequired();
                });

            modelBuilder.Entity("Credutpay.Domain.Registrations.Entities.Wallet", b =>
                {
                    b.Navigation("ReceiverTransactions");

                    b.Navigation("SentTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
